"""Payment read-path projections - ORM rows to the frozen wire shapes.

Spec references:
    API_CONTRACT section 15   the payment object.
    section 14.6 / section 109  ownership is applied in the query, never here. A
                 serializer that had to decide whether the caller may see a row
                 would be a post-load authorisation check, and one early ``return``
                 is all it takes for that to leak.
    INV-005      ``refundable_amount`` is read from the model property, never
                 recomputed here, so the refund cap has exactly one owner.

## Why a serializer and not ``model_validate(row)``

Three things happen here that no ORM projection can express:

1. **Derived, server-owned figures.** ``refundable_amount`` is the payment row's
   own property. Recomputing ``paid - refunded`` in the serializer would be the
   second implementation of an arithmetic rule that ``RefundWorkflow`` and a MySQL
   ``CHECK`` constraint both already enforce.
2. **Wire-name mapping.** ``external_transaction_no`` is the column;
   ``transaction_no`` is the frozen field. Doing that rename in one place means a
   reader of the contract can grep for it.
3. **Explicit absence.** Section 2 says an omitted field is never a silent
   ``null``; building the output field by field is what makes that checkable.

## What a payment payload deliberately does *not* contain

The callback list, the raw ``payload_snapshot`` and the ``request_hash``. The
snapshot is audit evidence (it can carry a provider's dispute reference), the hash
is an internal canonicalisation artefact, and neither belongs on a consumer
response. ``PaymentOut`` is the only projection here for exactly that reason: if a
console ever needs the callback history it gets its own projection, decided on
purpose, rather than inheriting fields because they happened to be on the row.
"""

from __future__ import annotations

from typing import Any

from app.modules.payment.enums import PaymentChannel
from app.modules.payment.schemas import CallbackAckOut, PaymentCreateOut, PaymentOut

__all__ = [
    "MOCK_PAY_URL_TEMPLATE",
    "pay_url_for",
    "to_callback_ack",
    "to_payment",
    "to_payment_create",
    "to_payment_list",
]

#: Where a mock-channel payment sends the browser.
#:
#: A **relative** API path, not an absolute URL, and that is deliberate: the backend
#: does not know the public hostname it is served under (a reverse proxy or a tunnel
#: decides that), and inventing one would produce a link that works in the
#: development compose file and 404s in every deployed environment. The path is the
#: one this API actually serves, so the client prefixes its own base URL.
MOCK_PAY_URL_TEMPLATE = "/api/v1/payments/customer/payments/{payment_id}/mock-pay"


def pay_url_for(channel: str, payment_no: str) -> str | None:
    """The MockPay redirect URL for a mock payment, ``None`` for a real provider.

    Section 15.2 freezes the rule: *"``pay_url`` is present only for
    ``channel = "MOCK"`` ... and is ``null`` otherwise"*. Encoding it as one function
    rather than an ``if`` at each call site is what keeps a future ``ALIPAY`` redirect
    from being emitted by accident - a real provider's URL is produced client-side by
    the provider's SDK, so echoing one from this API would mean the server had invented
    a payment URL, which is the one thing in this domain that must never be
    approximated.
    """
    if channel != PaymentChannel.MOCK.value:
        return None
    return MOCK_PAY_URL_TEMPLATE.format(payment_id=payment_no)


def to_payment(payment: Any) -> PaymentOut:
    """One payment row (API_CONTRACT section 15).

    Written against **attribute access only** and annotated ``Any`` on purpose: it
    must not import a model class, so a Phase 5 model change cannot turn a read
    path into an import error, and the serializer stays testable with a plain
    stand-in object in a unit test.

    ``pay_url`` follows the frozen rule of section 15.2 exactly: non-null **only**
    for ``channel = "MOCK"``, where it points at this API's own mock-pay endpoint,
    and ``null`` for every real provider (whose redirect URL is generated by the
    provider's SDK on the client). The frontend type declares the field optional, so
    it is emitted explicitly as ``null`` rather than omitted - section 2 says an
    omitted field is not a silent ``null``, and a client that checked
    ``'pay_url' in payment`` would otherwise be right today and wrong the day a real
    provider lands.
    """
    return PaymentOut(
        id=payment.id,
        payment_no=payment.payment_no,
        order_id=payment.order_id,
        order_no=payment.order_no,
        channel=payment.channel,
        status=payment.status,
        amount=payment.amount,
        paid_amount=payment.paid_amount,
        refunded_amount=payment.refunded_amount,
        # The model's own property - INV-005 has one owner.
        refundable_amount=payment.refundable_amount,
        pay_url=pay_url_for(payment.channel, payment.payment_no),
        external_transaction_no=payment.external_transaction_no,
        idempotency_key=payment.idempotency_key,
        expires_at=payment.expires_at,
        paid_at=payment.paid_at,
        created_at=payment.created_at,
        updated_at=payment.updated_at,
    )


def to_payment_create(payment: Any, *, replayed: bool, order_payment_status: str) -> PaymentCreateOut:
    """The create response: the payment plus the two facts a retry needs."""
    base = to_payment(payment)
    return PaymentCreateOut(
        **base.model_dump(),
        replayed=replayed,
        order_payment_status=order_payment_status,
    )


def to_payment_list(payments: list[Any]) -> list[PaymentOut]:
    """Project a page of payment rows, preserving the repository's order.

    Ordering is intentionally not re-sorted here. The repository orders by
    ``created_at DESC, id DESC`` - the id tiebreaker matters because two attempts
    created in the same millisecond share a ``DATETIME(3)`` value, and a list that
    reorders itself between requests is a support ticket waiting to happen.
    """
    return [to_payment(payment) for payment in payments]


def to_callback_ack(
    *,
    event_id: str,
    payment_no: str | None,
    processed: bool,
    replayed: bool = False,
    duplicate: bool = False,
    status: str | None = None,
) -> CallbackAckOut:
    """The provider-facing acknowledgement.

    Every parameter is keyword-only and explicit: this payload is the *only* thing
    a provider learns about the merchant's business, so it should be impossible to
    widen it by passing a row through. There is no ``dict``/``Any`` input by
    design.
    """
    return CallbackAckOut(
        event_id=event_id,
        payment_no=payment_no,
        processed=processed,
        replayed=replayed,
        duplicate=duplicate,
        status=status,
    )
