/**
 * ESLint flat config (ESLint 10, eslint-plugin-vue 10, TypeScript 6).
 *
 * NOTE ON TYPE-AWARE LINTING
 *  `typescript-eslint` 8.x declares a peer range of `typescript >=4.8.4 <6.1.0`, and the
 *  pinned toolchain here is TypeScript 6.0.x (see the note in `package.json` about
 *  vue-tsc). Type-aware rules are therefore NOT enabled, and the parser is configured
 *  without `project`. That is a deliberate, documented trade-off: `vue-tsc --noEmit` is
 *  the authoritative type check, and this config focuses on correctness and Vue/TS
 *  syntax hygiene that does not need type information.
 */

import js from '@eslint/js'
import pluginVue from 'eslint-plugin-vue'
import globals from 'globals'
import tsParser from '@typescript-eslint/parser'

export default [
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'coverage/**',
      'e2e/.artifacts/**',
      'src/types/generated/**',
      // Generated by unplugin-auto-import / unplugin-vue-components.
      'src/types/auto-imports.d.ts',
      'src/types/components.d.ts',
    ],
  },

  js.configs.recommended,
  ...pluginVue.configs['flat/essential'],

  {
    files: ['**/*.ts'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      parser: tsParser,
      globals: { ...globals.browser, ...globals.node },
    },
  },

  {
    files: ['**/*.vue'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      // `vue-eslint-parser` parses the SFC and delegates <script lang="ts"> to the TS
      // parser. Without an explicit `parser` here, TS syntax inside .vue is a parse error.
      parserOptions: { parser: tsParser },
      globals: { ...globals.browser },
    },
  },

  {
    files: ['**/*.{ts,vue}'],
    rules: {
      // `vue-tsc --noEmit` is the authoritative checker, and it understands the DOM lib.
      // ESLint's `no-undef` cannot see TS types (e.g. `RequestInit`), so it would only
      // produce false positives here. It stays ON for plain JS config files.
      'no-undef': 'off',

      // Vue 3 + <script setup> everywhere (REQ-FE-001).
      'vue/component-api-style': ['error', ['script-setup']],
      'vue/multi-word-component-names': 'off',

      // Unused code is a correctness smell. `_`-prefixed bindings are the documented
      // escape hatch (error boundaries, deliberately ignored event args).
      'no-unused-vars': 'off',

      // Empty catch blocks are intentional and commented at each site (storage
      // unavailable, best-effort logout).
      'no-empty': ['error', { allowEmptyCatch: true }],

      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'prefer-const': 'error',
      eqeqeq: ['error', 'always'],
    },
  },

  {
    files: [
      '**/*.spec.ts',
      'tests/**/*.ts',
      'e2e/**/*.ts',
      'vite.config.ts',
      'playwright.config.ts',
      'scripts/**/*.mjs',
      'eslint.config.js',
    ],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
    rules: {
      'no-console': 'off',
      // Specs deliberately assert on control characters (log-forging payloads and
      // sanitizer behaviour), so matching them is the point of the test.
      'no-control-regex': 'off',
    },
  },

  {
    // Formatting taste (attribute wrapping, singleline content) is NOT enforced: the
    // project has no Prettier step in the gate, so these would be noise, not signal.
    files: ['**/*.vue'],
    rules: {
      'vue/max-attributes-per-line': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/html-indent': 'off',
      'vue/html-self-closing': 'off',
      'vue/attributes-order': 'off',
    },
  },
]
