"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

Generated by Alembic. Review before committing - autogenerate is a draft, not a
verdict. In particular, verify that:

  * the downgrade path is genuinely correct (it is the disaster-recovery path);
  * CHECK constraints backing INV-001/INV-002 were not silently dropped;
  * money columns are BIGINT and never FLOAT/DOUBLE (spec section 19);
  * new columns on populated tables are nullable, or carry a server_default.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision: str = ${repr(up_revision)}
down_revision: str | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    """Apply the change."""
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    """Revert the change.

    Written out rather than left empty: an unrunnable downgrade turns a bad
    deploy into an unrecoverable one.
    """
    ${downgrades if downgrades else "pass"}
