// One-shot brand rename: Nova -> Nova (frontend/ only).
//
// Case-sensitive as two explicit replacements, because a case-insensitive sweep would
// also rewrite unrelated words. Specifically NOT touched:
//   * `nx-*` CSS prefix / `--nx-*` custom properties — our own namespace, never carried
//     the brand name (627 usages); renaming it would be churn with real regression risk.
//   * `cookie?: never` in src/types/generated/api.d.ts — that is the HTTP `Cookie`
//     header from the OpenAPI document, not a brand string. Regenerated by `npm run gen:api`.
//   * `js-cookie` / `tough-cookie` entries in package-lock.json — third-party package names.
//   * `docs/nova-v1/` (the team-state directory) — outside frontend/ and not ours to edit.
//
// Prints one line per file with the number of substitutions, then hard-fails if any
// occurrence survives, so "I renamed everything" is verified rather than asserted.

import { globSync, readFileSync, writeFileSync } from 'node:fs'

const EXTENSIONS = ['ts', 'vue', 'json', 'html', 'md', 'scss', 'css', 'mjs']
const IGNORE = /node_modules|\\dist\/|\/dist\//
// package-lock.json intentionally excluded: `npm install` regenerates its `name` field
// from package.json, which is more trustworthy than a text edit.
const SKIP_FILES = [/package-lock\.json$/, /api\.d\.ts$/]

const files = []
for (const ext of EXTENSIONS) {
  for (const match of globSync(`**/*.${ext}`, { cwd: process.cwd(), withFileTypes: false })) {
    if (IGNORE.test(match) || SKIP_FILES.some((re) => re.test(match))) continue
    files.push(match)
  }
}

let totalFiles = 0
let totalSubs = 0

for (const file of files.sort()) {
  const before = readFileSync(file, 'utf8')
  if (!/Nova|nova/.test(before)) continue

  const after = before.replaceAll('Nova', 'Nova').replaceAll('nova', 'nova')
  const count =
    (before.match(/Nova/g) ?? []).length + (before.match(/nova/g) ?? []).length

  writeFileSync(file, after, 'utf8')
  totalFiles += 1
  totalSubs += count
  console.log(`  ${file.padEnd(46)} ${count} substitution(s)`)
}

console.log(`\nrenamed ${totalSubs} occurrence(s) across ${totalFiles} file(s)`)

// Verification pass: re-scan everything (including the skipped files) and fail loudly.
const leftovers = []
for (const ext of EXTENSIONS) {
  for (const match of globSync(`**/*.${ext}`, { cwd: process.cwd(), withFileTypes: false })) {
    if (IGNORE.test(match)) continue
    if (/api\.d\.ts$/.test(match)) continue
    const text = readFileSync(match, 'utf8')
    const lines = text.split('\n')
    lines.forEach((line, index) => {
      if (/Nova|nova/.test(line)) {
        leftovers.push(`${match}:${index + 1}: ${line.trim()}`)
      }
    })
  }
}

if (leftovers.length > 0) {
  console.error(`\nFAILED: ${leftovers.length} occurrence(s) still present:`)
  for (const line of leftovers) console.error(`  ${line}`)
  process.exit(1)
}

console.log('verified: no "Nova"/"nova" remains (package-lock.json handled by npm install)')
