"""phase6 promotions

Revision ID: 40c9914d7367
Revises: 48f1e3b5a00c
Create Date: 2026-09-24 01:49:23.656651

Generated by Alembic. Review before committing - autogenerate is a draft, not a
verdict. In particular, verify that:

  * the downgrade path is genuinely correct (it is the disaster-recovery path);
  * CHECK constraints backing INV-001/INV-002 were not silently dropped;
  * money columns are BIGINT and never FLOAT/DOUBLE (spec section 19);
  * new columns on populated tables are nullable, or carry a server_default.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.shared.db.types

# revision identifiers, used by Alembic.
revision: str = "40c9914d7367"
down_revision: str | None = "48f1e3b5a00c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promotions",
        sa.Column("promotion_no", sa.String(length=32), nullable=False),
        sa.Column("preview_token_hash", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("promotion_type", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="DRAFT", nullable=False),
        sa.Column("priority", sa.Integer(), server_default="100", nullable=False),
        sa.Column("stackable", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("rule_config", sa.JSON(), nullable=False),
        sa.Column("scope", sa.JSON(), nullable=False),
        sa.Column("starts_at", app.shared.db.types.DateTimeMS(), nullable=False),
        sa.Column("ends_at", app.shared.db.types.DateTimeMS(), nullable=False),
        sa.Column("total_quota", sa.Integer(), nullable=False),
        sa.Column("used_quota", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.CheckConstraint(
            "promotion_type IN ('DIRECT_DISCOUNT','PERCENT_DISCOUNT','FULL_REDUCTION')",
            name=op.f("ck_promotions_type_valid"),
        ),
        sa.CheckConstraint("status IN ('DRAFT','ACTIVE','ENDED')", name=op.f("ck_promotions_status_valid")),
        sa.CheckConstraint("starts_at < ends_at", name=op.f("ck_promotions_window_valid")),
        sa.CheckConstraint(
            "total_quota >= 0 AND used_quota >= 0 AND used_quota <= total_quota",
            name=op.f("ck_promotions_quota_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_promotions_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promotions")),
        sa.UniqueConstraint("merchant_id", "promotion_no", name="uq_promotions_merchant_no"),
        sa.UniqueConstraint("merchant_id", "preview_token_hash", name="uq_promotions_preview_token"),
    )
    op.create_index(op.f("ix_promotions_created_at"), "promotions", ["created_at"], unique=False)
    op.create_index(
        "ix_promotions_merchant_active_window",
        "promotions",
        ["merchant_id", "status", "starts_at", "ends_at"],
        unique=False,
    )
    op.create_index(op.f("ix_promotions_merchant_id"), "promotions", ["merchant_id"], unique=False)
    op.create_index("ix_promotions_priority", "promotions", ["priority", "id"], unique=False)
    op.create_table(
        "promotion_products",
        sa.Column("promotion_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("product_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_promotion_products_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_promotion_products_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["promotion_id"],
            ["promotions.id"],
            name=op.f("fk_promotion_products_promotion_id_promotions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promotion_products")),
        sa.UniqueConstraint("promotion_id", "product_id", name="uq_promotion_products_pair"),
    )
    op.create_index(
        op.f("ix_promotion_products_created_at"), "promotion_products", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_promotion_products_merchant_id"), "promotion_products", ["merchant_id"], unique=False
    )
    op.create_index(
        "ix_promotion_products_product", "promotion_products", ["product_id", "promotion_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop dependent rows before their promotion parents."""
    op.drop_table("promotion_products")
    op.drop_table("promotions")
