"""phase6 coupon lifecycle

Revision ID: f0d29969cfb5
Revises: 40c9914d7367
Create Date: 2026-09-24 02:13:58.781451

Generated by Alembic. Review before committing - autogenerate is a draft, not a
verdict. In particular, verify that:

  * the downgrade path is genuinely correct (it is the disaster-recovery path);
  * CHECK constraints backing INV-001/INV-002 were not silently dropped;
  * money columns are BIGINT and never FLOAT/DOUBLE (spec section 19);
  * new columns on populated tables are nullable, or carry a server_default.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.shared.db.types

# revision identifiers, used by Alembic.
revision: str = "f0d29969cfb5"
down_revision: str | None = "40c9914d7367"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coupon_templates",
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("template_no", sa.String(length=32), nullable=False),
        sa.Column("preview_token_hash", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("coupon_type", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="DRAFT", nullable=False),
        sa.Column("face_value_amount", app.shared.db.types.MoneyMinor(), nullable=True),
        sa.Column("discount_bps", sa.Integer(), nullable=True),
        sa.Column("threshold_amount", app.shared.db.types.MoneyMinor(), server_default="0", nullable=False),
        sa.Column("max_discount_amount", app.shared.db.types.MoneyMinor(), nullable=True),
        sa.Column("total_quota", sa.Integer(), nullable=False),
        sa.Column("issued_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("per_user_limit", sa.Integer(), nullable=False),
        sa.Column("validity_type", sa.String(length=16), nullable=False),
        sa.Column("valid_days", sa.Integer(), nullable=True),
        sa.Column("valid_from", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("valid_to", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("applicable_scope", sa.JSON(), nullable=False),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.CheckConstraint(
            "(coupon_type = 'FIXED_AMOUNT' AND face_value_amount > 0 AND discount_bps IS NULL "
            "AND max_discount_amount IS NULL) OR (coupon_type = 'PERCENT_DISCOUNT' "
            "AND face_value_amount IS NULL AND discount_bps BETWEEN 1 AND 10000)",
            name=op.f("ck_coupon_templates_value_valid"),
        ),
        sa.CheckConstraint(
            "(validity_type = 'RELATIVE' AND valid_days > 0 AND valid_from IS NULL AND valid_to IS NULL) OR (validity_type = 'ABSOLUTE' AND valid_days IS NULL AND valid_from < valid_to)",
            name=op.f("ck_coupon_templates_validity_valid"),
        ),
        sa.CheckConstraint(
            "threshold_amount >= 0 AND (max_discount_amount IS NULL OR max_discount_amount > 0)",
            name=op.f("ck_coupon_templates_amount_valid"),
        ),
        sa.CheckConstraint(
            "coupon_type IN ('FIXED_AMOUNT','PERCENT_DISCOUNT')", name=op.f("ck_coupon_templates_type_valid")
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','ACTIVE','ENDED')", name=op.f("ck_coupon_templates_status_valid")
        ),
        sa.CheckConstraint(
            "total_quota > 0 AND issued_count >= 0 AND issued_count <= total_quota AND per_user_limit > 0",
            name=op.f("ck_coupon_templates_quota_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_coupon_templates_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupon_templates")),
        sa.UniqueConstraint("merchant_id", "preview_token_hash", name="uq_coupon_templates_preview_token"),
        sa.UniqueConstraint("merchant_id", "template_no", name="uq_coupon_templates_merchant_no"),
    )
    op.create_index(op.f("ix_coupon_templates_created_at"), "coupon_templates", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_coupon_templates_merchant_id"), "coupon_templates", ["merchant_id"], unique=False
    )
    op.create_index(
        "ix_coupon_templates_merchant_status", "coupon_templates", ["merchant_id", "status"], unique=False
    )
    op.create_table(
        "user_coupons",
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("template_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("user_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="UNUSED", nullable=False),
        sa.Column("valid_from", app.shared.db.types.DateTimeMS(), nullable=False),
        sa.Column("valid_to", app.shared.db.types.DateTimeMS(), nullable=False),
        sa.Column("order_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("locked_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("used_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.CheckConstraint(
            "status IN ('UNUSED','LOCKED','USED','EXPIRED')", name=op.f("ck_user_coupons_status_valid")
        ),
        sa.CheckConstraint("valid_from < valid_to", name=op.f("ck_user_coupons_window_valid")),
        sa.CheckConstraint(
            "(status IN ('UNUSED','EXPIRED') AND order_id IS NULL) "
            "OR (status IN ('LOCKED','USED') AND order_id IS NOT NULL)",
            name=op.f("ck_user_coupons_order_lock_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_user_coupons_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_user_coupons_order_id_orders"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["coupon_templates.id"],
            name=op.f("fk_user_coupons_template_id_coupon_templates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_coupons_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_coupons")),
    )
    op.create_index(op.f("ix_user_coupons_created_at"), "user_coupons", ["created_at"], unique=False)
    op.create_index(op.f("ix_user_coupons_merchant_id"), "user_coupons", ["merchant_id"], unique=False)
    op.create_index(op.f("ix_user_coupons_order_id"), "user_coupons", ["order_id"], unique=False)
    op.create_index(op.f("ix_user_coupons_template_id"), "user_coupons", ["template_id"], unique=False)
    op.create_index(op.f("ix_user_coupons_user_id"), "user_coupons", ["user_id"], unique=False)
    op.create_index(
        "ix_user_coupons_user_status_expiry", "user_coupons", ["user_id", "status", "valid_to"], unique=False
    )
    op.create_table(
        "coupon_usage_records",
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("user_coupon_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("order_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.CheckConstraint(
            "action IN ('LOCK','USE','RELEASE')", name=op.f("ck_coupon_usage_records_action_valid")
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_coupon_usage_records_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_coupon_usage_records_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_coupon_id"],
            ["user_coupons.id"],
            name=op.f("fk_coupon_usage_records_user_coupon_id_user_coupons"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupon_usage_records")),
        sa.UniqueConstraint("user_coupon_id", "order_id", "action", name="uq_coupon_usage_action"),
    )
    op.create_index(
        op.f("ix_coupon_usage_records_created_at"), "coupon_usage_records", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_coupon_usage_records_merchant_id"), "coupon_usage_records", ["merchant_id"], unique=False
    )
    op.create_index(
        op.f("ix_coupon_usage_records_order_id"), "coupon_usage_records", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_coupon_usage_records_user_coupon_id"),
        "coupon_usage_records",
        ["user_coupon_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the change.

    Written out rather than left empty: an unrunnable downgrade turns a bad
    deploy into an unrecoverable one.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("coupon_usage_records")
    op.drop_table("user_coupons")
    op.drop_table("coupon_templates")
    # ### end Alembic commands ###
