"""catalog_and_inventory

Revision ID: 05b3d5f5348b
Revises: 678c0e1de548
Create Date: 2026-09-23 08:13:44.222710

Generated by Alembic. Review before committing - autogenerate is a draft, not a
verdict. In particular, verify that:

  * the downgrade path is genuinely correct (it is the disaster-recovery path);
  * CHECK constraints backing INV-001/INV-002 were not silently dropped;
  * money columns are BIGINT and never FLOAT/DOUBLE (spec section 19);
  * new columns on populated tables are nullable, or carry a server_default.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

import app.shared.db.types

# revision identifiers, used by Alembic.
revision: str = "05b3d5f5348b"
down_revision: str | None = "678c0e1de548"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("name_en", sa.String(length=128), nullable=True),
        sa.Column("logo_object_key", sa.String(length=512), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("deleted_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_brands_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
        sa.UniqueConstraint("merchant_id", "name", name="uq_brands_merchant_name"),
    )
    op.create_index(op.f("ix_brands_created_at"), "brands", ["created_at"], unique=False)
    op.create_index(op.f("ix_brands_deleted_at"), "brands", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_brands_merchant_id"), "brands", ["merchant_id"], unique=False)
    op.create_table(
        "categories",
        sa.Column("parent_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("depth", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_leaf", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("icon_object_key", sa.String(length=512), nullable=True),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("deleted_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.CheckConstraint("depth >= 0", name=op.f("ck_categories_depth_non_negative")),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_categories_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("merchant_id", "code", name="uq_categories_merchant_code"),
    )
    op.create_index(op.f("ix_categories_created_at"), "categories", ["created_at"], unique=False)
    op.create_index(op.f("ix_categories_deleted_at"), "categories", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_categories_merchant_id"), "categories", ["merchant_id"], unique=False)
    op.create_index("ix_categories_parent_sort", "categories", ["parent_id", "sort_order"], unique=False)
    op.create_table(
        "warehouses",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="ACTIVE", nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("address", sa.String(length=512), nullable=True),
        sa.Column("contact_name", sa.String(length=64), nullable=True),
        sa.Column("contact_phone", sa.String(length=32), nullable=True),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("deleted_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name=op.f("ck_warehouses_status_valid")),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_warehouses_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouses")),
        sa.UniqueConstraint("merchant_id", "code", name="uq_warehouses_merchant_code"),
    )
    op.create_index(op.f("ix_warehouses_created_at"), "warehouses", ["created_at"], unique=False)
    op.create_index(op.f("ix_warehouses_deleted_at"), "warehouses", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_warehouses_merchant_id"), "warehouses", ["merchant_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("product_no", sa.String(length=32), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("subtitle", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("brand_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="DRAFT", nullable=False),
        sa.Column("published_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("unpublished_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("min_price", app.shared.db.types.MoneyMinor(), server_default="0", nullable=False),
        sa.Column("max_price", app.shared.db.types.MoneyMinor(), server_default="0", nullable=False),
        sa.Column("primary_image_object_key", sa.String(length=512), nullable=True),
        sa.Column("sales_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("extra_json", sa.JSON(), nullable=True),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("deleted_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','PUBLISHED','UNPUBLISHED','ARCHIVED')", name=op.f("ck_products_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brands.id"], name=op.f("fk_products_brand_id_brands"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_products_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_products_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("merchant_id", "product_no", name="uq_products_merchant_no"),
        sa.UniqueConstraint("merchant_id", "slug", name="uq_products_merchant_slug"),
    )
    op.create_index("ix_products_brand_status", "products", ["brand_id", "status"], unique=False)
    op.create_index("ix_products_category_status", "products", ["category_id", "status"], unique=False)
    op.create_index(op.f("ix_products_created_at"), "products", ["created_at"], unique=False)
    op.create_index(op.f("ix_products_deleted_at"), "products", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_products_merchant_id"), "products", ["merchant_id"], unique=False)
    op.create_index("ix_products_status_published", "products", ["status", "published_at"], unique=False)
    op.create_table(
        "product_attributes",
        sa.Column("product_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("name", sa.String(length=96), nullable=False),
        sa.Column("value_type", sa.String(length=32), server_default="TEXT", nullable=False),
        sa.Column("is_variant_axis", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("is_searchable", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("unit", sa.String(length=24), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.CheckConstraint(
            "value_type IN ('TEXT','NUMBER','SELECT','BOOLEAN')",
            name=op.f("ck_product_attributes_value_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_product_attributes_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_attributes_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_attributes")),
        sa.UniqueConstraint("product_id", "name", name="uq_product_attributes_product_name"),
    )
    op.create_index(
        op.f("ix_product_attributes_created_at"), "product_attributes", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_product_attributes_merchant_id"), "product_attributes", ["merchant_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_attributes_product_id"), "product_attributes", ["product_id"], unique=False
    )
    op.create_index(
        "ix_product_attributes_product_variant",
        "product_attributes",
        ["product_id", "is_variant_axis"],
        unique=False,
    )
    op.create_table(
        "product_skus",
        sa.Column("product_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("sku_no", sa.String(length=32), nullable=False),
        sa.Column("sku_code", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("price_amount", app.shared.db.types.MoneyMinor(), nullable=False),
        sa.Column(
            "market_price_amount", app.shared.db.types.MoneyMinor(), server_default="0", nullable=False
        ),
        sa.Column("cost_amount", app.shared.db.types.MoneyMinor(), server_default="0", nullable=False),
        sa.Column("status", sa.String(length=32), server_default="ACTIVE", nullable=False),
        sa.Column("purchase_limit", sa.Integer(), server_default="0", nullable=False),
        sa.Column("weight_grams", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("attribute_snapshot", sa.JSON(), nullable=True),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("deleted_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ACTIVE','INACTIVE','DISCONTINUED')", name=op.f("ck_product_skus_status_valid")
        ),
        sa.CheckConstraint("cost_amount >= 0", name=op.f("ck_product_skus_cost_non_negative")),
        sa.CheckConstraint(
            "market_price_amount >= 0", name=op.f("ck_product_skus_market_price_non_negative")
        ),
        sa.CheckConstraint("price_amount >= 0", name=op.f("ck_product_skus_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_product_skus_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_skus_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_skus")),
        sa.UniqueConstraint("merchant_id", "sku_no", name="uq_product_skus_merchant_no"),
        sa.UniqueConstraint("sku_code", name="uq_product_skus_code"),
    )
    op.create_index(op.f("ix_product_skus_created_at"), "product_skus", ["created_at"], unique=False)
    op.create_index(op.f("ix_product_skus_deleted_at"), "product_skus", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_product_skus_merchant_id"), "product_skus", ["merchant_id"], unique=False)
    op.create_index(op.f("ix_product_skus_product_id"), "product_skus", ["product_id"], unique=False)
    op.create_index("ix_product_skus_product_status", "product_skus", ["product_id", "status"], unique=False)
    op.create_table(
        "inventories",
        sa.Column("warehouse_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("sku_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("available_qty", app.shared.db.types.BigIntUnsigned(), server_default="0", nullable=False),
        sa.Column("locked_qty", app.shared.db.types.BigIntUnsigned(), server_default="0", nullable=False),
        sa.Column("safety_stock", app.shared.db.types.BigIntUnsigned(), server_default="0", nullable=False),
        sa.Column("total_in_qty", app.shared.db.types.BigIntUnsigned(), server_default="0", nullable=False),
        sa.Column("total_out_qty", app.shared.db.types.BigIntUnsigned(), server_default="0", nullable=False),
        sa.Column("version", app.shared.db.types.BigIntUnsigned(), server_default="1", nullable=False),
        sa.Column("last_movement_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("last_counted_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.CheckConstraint("available_qty >= 0", name=op.f("ck_inventories_available_non_negative")),
        sa.CheckConstraint("locked_qty >= 0", name=op.f("ck_inventories_locked_non_negative")),
        sa.CheckConstraint("safety_stock >= 0", name=op.f("ck_inventories_safety_stock_non_negative")),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_inventories_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["product_skus.id"],
            name=op.f("fk_inventories_sku_id_product_skus"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventories_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventories")),
        sa.UniqueConstraint("warehouse_id", "sku_id", name="uq_inventories_warehouse_sku"),
    )
    op.create_index(op.f("ix_inventories_created_at"), "inventories", ["created_at"], unique=False)
    op.create_index("ix_inventories_low_stock", "inventories", ["sku_id", "available_qty"], unique=False)
    op.create_index(op.f("ix_inventories_merchant_id"), "inventories", ["merchant_id"], unique=False)
    op.create_index("ix_inventories_sku", "inventories", ["sku_id"], unique=False)
    op.create_table(
        "inventory_movements",
        sa.Column("warehouse_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("sku_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("movement_type", sa.String(length=32), nullable=False),
        sa.Column("delta_available", sa.Integer(), nullable=False),
        sa.Column("delta_locked", sa.Integer(), nullable=False),
        sa.Column("before_available", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("after_available", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("before_locked", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("after_locked", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("reference_type", sa.String(length=32), nullable=False),
        sa.Column("reference_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("operator_type", sa.String(length=32), nullable=False),
        sa.Column("operator_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.String(length=512), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.CheckConstraint(
            "movement_type IN ('PURCHASE_IN','ORDER_LOCK','ORDER_RELEASE','ORDER_DEDUCT','RETURN_IN','MANUAL_ADJUST','DAMAGED_OUT')",
            name=op.f("ck_inventory_movements_movement_type_valid"),
        ),
        sa.CheckConstraint(
            "operator_type IN ('SYSTEM','CUSTOMER','STAFF','AGENT','MCP','WORKER')",
            name=op.f("ck_inventory_movements_operator_type_valid"),
        ),
        sa.CheckConstraint(
            "after_available >= 0", name=op.f("ck_inventory_movements_after_available_non_negative")
        ),
        sa.CheckConstraint(
            "after_locked >= 0", name=op.f("ck_inventory_movements_after_locked_non_negative")
        ),
        sa.CheckConstraint(
            "before_available >= 0", name=op.f("ck_inventory_movements_before_available_non_negative")
        ),
        sa.CheckConstraint(
            "before_locked >= 0", name=op.f("ck_inventory_movements_before_locked_non_negative")
        ),
        sa.CheckConstraint(
            "delta_available = after_available - before_available",
            name=op.f("ck_inventory_movements_delta_available_consistent"),
        ),
        sa.CheckConstraint(
            "delta_locked = after_locked - before_locked",
            name=op.f("ck_inventory_movements_delta_locked_consistent"),
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["product_skus.id"],
            name=op.f("fk_inventory_movements_sku_id_product_skus"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_movements_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_movements")),
        sa.UniqueConstraint("idempotency_key", name="uq_inventory_movements_idempotency_key"),
    )
    op.create_index(
        op.f("ix_inventory_movements_created_at"), "inventory_movements", ["created_at"], unique=False
    )
    op.create_index(
        "ix_inventory_movements_reference",
        "inventory_movements",
        ["reference_type", "reference_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_movements_sku_created", "inventory_movements", ["sku_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_inventory_movements_type_created",
        "inventory_movements",
        ["movement_type", "created_at"],
        unique=False,
    )
    op.create_table(
        "product_images",
        sa.Column("product_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("sku_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("bucket", sa.String(length=96), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=96), nullable=False),
        sa.Column("size_bytes", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("role", sa.String(length=32), server_default="GALLERY", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("alt_text", sa.String(length=255), nullable=True),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.CheckConstraint(
            "object_key NOT LIKE '/%%' AND object_key NOT LIKE '%%..%%'",
            name=op.f("ck_product_images_object_key_relative_and_safe"),
        ),
        sa.CheckConstraint(
            "role IN ('PRIMARY','GALLERY','DETAIL')", name=op.f("ck_product_images_role_valid")
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_product_images_size_non_negative")),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_product_images_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_images_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["product_skus.id"],
            name=op.f("fk_product_images_sku_id_product_skus"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_images")),
        sa.UniqueConstraint("object_key", name="uq_product_images_object_key"),
    )
    op.create_index(op.f("ix_product_images_created_at"), "product_images", ["created_at"], unique=False)
    op.create_index(op.f("ix_product_images_merchant_id"), "product_images", ["merchant_id"], unique=False)
    op.create_index(op.f("ix_product_images_product_id"), "product_images", ["product_id"], unique=False)
    op.create_index(
        "ix_product_images_product_role_sort",
        "product_images",
        ["product_id", "role", "sort_order"],
        unique=False,
    )
    op.create_table(
        "sku_attribute_values",
        sa.Column("sku_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("attribute_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=False),
        sa.Column("display_value", sa.String(length=64), nullable=True),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["product_attributes.id"],
            name=op.f("fk_sku_attribute_values_attribute_id_product_attributes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["product_skus.id"],
            name=op.f("fk_sku_attribute_values_sku_id_product_skus"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sku_attribute_values")),
        sa.UniqueConstraint("sku_id", "attribute_id", name="uq_sku_attribute_values_pair"),
    )
    op.create_index(
        "ix_sku_attribute_values_attribute", "sku_attribute_values", ["attribute_id"], unique=False
    )
    op.create_index(
        op.f("ix_sku_attribute_values_created_at"), "sku_attribute_values", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_sku_attribute_values_sku_id"), "sku_attribute_values", ["sku_id"], unique=False)
    op.alter_column(
        "auth_sessions",
        "created_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("now(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "auth_sessions",
        "updated_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("now(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "merchants",
        "created_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("now(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "merchants",
        "updated_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("now(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "permissions",
        "created_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("now(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "permissions",
        "updated_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("now(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "role_permissions",
        "created_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("now(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "role_permissions",
        "updated_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("now(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "roles",
        "created_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("now(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "roles",
        "updated_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("now(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_addresses",
        "created_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("now(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_addresses",
        "updated_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("now(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_roles",
        "created_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("now(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_roles",
        "updated_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("now(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("now(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("now(3)"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the change.

    Written out rather than left empty: an unrunnable downgrade turns a bad
    deploy into an unrecoverable one.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "updated_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("CURRENT_TIMESTAMP(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("CURRENT_TIMESTAMP(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_roles",
        "updated_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("CURRENT_TIMESTAMP(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_roles",
        "created_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("CURRENT_TIMESTAMP(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_addresses",
        "updated_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("CURRENT_TIMESTAMP(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_addresses",
        "created_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("CURRENT_TIMESTAMP(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "roles",
        "updated_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("CURRENT_TIMESTAMP(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "roles",
        "created_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("CURRENT_TIMESTAMP(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "role_permissions",
        "updated_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("CURRENT_TIMESTAMP(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "role_permissions",
        "created_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("CURRENT_TIMESTAMP(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "permissions",
        "updated_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("CURRENT_TIMESTAMP(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "permissions",
        "created_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("CURRENT_TIMESTAMP(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "merchants",
        "updated_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("CURRENT_TIMESTAMP(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "merchants",
        "created_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("CURRENT_TIMESTAMP(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "auth_sessions",
        "updated_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("CURRENT_TIMESTAMP(3)"),
        existing_nullable=False,
    )
    op.alter_column(
        "auth_sessions",
        "created_at",
        existing_type=mysql.DATETIME(fsp=3),
        server_default=sa.text("CURRENT_TIMESTAMP(3)"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_sku_attribute_values_sku_id"), table_name="sku_attribute_values")
    op.drop_index(op.f("ix_sku_attribute_values_created_at"), table_name="sku_attribute_values")
    op.drop_index("ix_sku_attribute_values_attribute", table_name="sku_attribute_values")
    op.drop_table("sku_attribute_values")
    op.drop_index("ix_product_images_product_role_sort", table_name="product_images")
    op.drop_index(op.f("ix_product_images_product_id"), table_name="product_images")
    op.drop_index(op.f("ix_product_images_merchant_id"), table_name="product_images")
    op.drop_index(op.f("ix_product_images_created_at"), table_name="product_images")
    op.drop_table("product_images")
    op.drop_index("ix_inventory_movements_type_created", table_name="inventory_movements")
    op.drop_index("ix_inventory_movements_sku_created", table_name="inventory_movements")
    op.drop_index("ix_inventory_movements_reference", table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_created_at"), table_name="inventory_movements")
    op.drop_table("inventory_movements")
    op.drop_index("ix_inventories_sku", table_name="inventories")
    op.drop_index(op.f("ix_inventories_merchant_id"), table_name="inventories")
    op.drop_index("ix_inventories_low_stock", table_name="inventories")
    op.drop_index(op.f("ix_inventories_created_at"), table_name="inventories")
    op.drop_table("inventories")
    op.drop_index("ix_product_skus_product_status", table_name="product_skus")
    op.drop_index(op.f("ix_product_skus_product_id"), table_name="product_skus")
    op.drop_index(op.f("ix_product_skus_merchant_id"), table_name="product_skus")
    op.drop_index(op.f("ix_product_skus_deleted_at"), table_name="product_skus")
    op.drop_index(op.f("ix_product_skus_created_at"), table_name="product_skus")
    op.drop_table("product_skus")
    op.drop_index("ix_product_attributes_product_variant", table_name="product_attributes")
    op.drop_index(op.f("ix_product_attributes_product_id"), table_name="product_attributes")
    op.drop_index(op.f("ix_product_attributes_merchant_id"), table_name="product_attributes")
    op.drop_index(op.f("ix_product_attributes_created_at"), table_name="product_attributes")
    op.drop_table("product_attributes")
    op.drop_index("ix_products_status_published", table_name="products")
    op.drop_index(op.f("ix_products_merchant_id"), table_name="products")
    op.drop_index(op.f("ix_products_deleted_at"), table_name="products")
    op.drop_index(op.f("ix_products_created_at"), table_name="products")
    op.drop_index("ix_products_category_status", table_name="products")
    op.drop_index("ix_products_brand_status", table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_warehouses_merchant_id"), table_name="warehouses")
    op.drop_index(op.f("ix_warehouses_deleted_at"), table_name="warehouses")
    op.drop_index(op.f("ix_warehouses_created_at"), table_name="warehouses")
    op.drop_table("warehouses")
    op.drop_index("ix_categories_parent_sort", table_name="categories")
    op.drop_index(op.f("ix_categories_merchant_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_deleted_at"), table_name="categories")
    op.drop_index(op.f("ix_categories_created_at"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_brands_merchant_id"), table_name="brands")
    op.drop_index(op.f("ix_brands_deleted_at"), table_name="brands")
    op.drop_index(op.f("ix_brands_created_at"), table_name="brands")
    op.drop_table("brands")
    # ### end Alembic commands ###
