"""phase5 payment fulfillment aftersales and refund

Revision ID: 3f1ae2c55c54
Revises: a7c4e91b2d63
Create Date: 2026-09-23 16:43:03.000000

Phase 5 (``docs/architecture/PHASE5_DESIGN.md`` sections 5 and 8) adds the six
tables that make money-in, goods-out and money-out real records, plus the two
CHECK constraints that bound a refund at the database boundary:

    payments, payment_callbacks,
    fulfillments, fulfillment_items,
    after_sales, after_sale_items, refunds
    + orders.refunded_amount <= paid_amount
    + order_items.refunded_amount <= payable_amount

## Why this file is hand-written

Alembic generated the skeleton, and this file was reviewed against it rather than
trusted. Two MySQL behaviours recorded in ``HANDOFF.md`` section 6 make reviewing
mandatory rather than polite:

* **Alembic does not autogenerate CHECK-constraint changes on MySQL.** So the two
  new ``CHECK`` constraints on the *existing* ``orders`` / ``order_items`` tables
  appear in **no** autogenerated diff at all. They are written out by hand below,
  in ``op.create_check_constraint``. Had they been forgotten, `alembic check` would
  still have reported a clean tree while the database had no cap - which is exactly
  the failure mode FG-12 exists to catch, and the reason the DDL is read back from
  ``information_schema`` instead of being inferred from an exit code.
* **``compare_type`` does not distinguish BIGINT from BIGINT UNSIGNED.** Every
  money column here is signed ``BIGINT`` (``MoneyMinor``) on purpose, for the
  arithmetic reason given below, and the signedness is invisible to autogenerate.

## The signed-money decision (do not "tidy" this)

Every money column is signed ``BIGINT``, and so is every column that appears in a
constraint with arithmetic in it. MySQL promotes a mixed signed/unsigned
comparison to UNSIGNED, so a single unsigned operand makes ``refunded_amount <=
paid_amount`` reject arithmetically correct rows - and, worse, makes a *negative*
intermediate overflow rather than fail. ``20260923_1235_5cbebbc7b364`` records the
hour FG-09 lost to exactly this on the stock ledger. Every operand below is signed,
so no ``CAST`` is needed anywhere.

## Table order, and why it is not alphabetical

``upgrade()`` creates in dependency order: ``payments`` before ``refunds`` (which
references it), ``fulfillments`` before ``fulfillment_items``, ``after_sales``
before ``after_sale_items`` and ``refunds``. ``downgrade()`` is the exact reverse
**plus** the two constraint drops, and the two constraint drops come **first** in
the downgrade because they are on pre-existing tables: dropping them last would
leave a window in which ``orders`` still carries a cap that Phase 4 never had,
while the columns behind it are being unwound. It is written out in full because an
runnable downgrade is what turns a bad deploy into a recoverable one.

## Deliberately absent

* **No ``op.drop_index`` in ``downgrade()``.** The first Phase 4 downgrade dropped
  indexes before tables and failed with errno 1553 ("Cannot drop index ... needed in
  a foreign key constraint"): ``DROP TABLE`` removes a table's indexes with it, so
  the explicit drops were not merely unnecessary, they were the bug - and because
  MySQL DDL is non-transactional, that failure left the database half-downgraded.
  This file does not repeat it.
* **No FK from ``payment_callbacks`` to ``payments``.** A callback routinely
  arrives for a ``payment_no`` that resolves to nothing, and that delivery must
  still be *recordable* as FAILED/IGNORED for triage. A FK would make the record
  impossible to keep, so the audit trail would lose precisely the events an
  operator most needs. ``merchant_id``/``payment_no``/``order_no`` are denormalised
  columns by design.
* **No unique constraint on ``fulfillments.order_id``.** The tempting
  ``UNIQUE (order_id)`` would encode "one order ships once" into the schema and make
  a split shipment (REQ-FUL-001) impossible to record without a migration.
* **No ``CHECK (refunded_amount <= approved_amount)`` on ``after_sales``.** The
  design says so explicitly (section 5.5): an operator may approve more than was
  requested when policy allows it, which V1 forbids in the service rather than in
  the schema. A policy question is not a constraint.
* **No per-line cumulative refund cap as a constraint.** It is a sum over refunds
  per line, so MySQL cannot express it; ``RefundWorkflow`` enforces it against
  freshly locked rows and FG-12 proves it with a negative control.

## Verification

After ``alembic upgrade head`` the following were read back and matched against the
constraints declared here - the six tables, every ``CHECK`` name above, and the
signedness of every money column::

    SELECT tc.TABLE_NAME, tc.CONSTRAINT_NAME, cc.CHECK_CLAUSE
      FROM information_schema.TABLE_CONSTRAINTS tc
      JOIN information_schema.CHECK_CONSTRAINTS cc
        ON cc.CONSTRAINT_SCHEMA = tc.CONSTRAINT_SCHEMA
       AND cc.CONSTRAINT_NAME   = tc.CONSTRAINT_NAME
     WHERE tc.TABLE_SCHEMA = DATABASE()
       AND tc.CONSTRAINT_TYPE = 'CHECK';

(``information_schema.CHECK_CONSTRAINTS`` has no ``TABLE_NAME`` in MySQL 8.4, so
the join through ``TABLE_CONSTRAINTS`` is required - another entry in
``HANDOFF.md`` section 6.) The raw output is committed at
``artifacts/evidence/integration/phase5_ddl_verification.md``, and the round trip
(``downgrade -1`` then ``upgrade head``) was executed rather than assumed.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.shared.db.types

# revision identifiers, used by Alembic.
revision: str = "3f1ae2c55c54"
down_revision: str | None = "a7c4e91b2d63"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---------------------------------------------------------------------------
# Vocabularies
#
# Duplicated from the Python enums on purpose: a migration must describe the
# schema *as of this revision* and must keep working even after an enum gains a
# member in a later phase. Importing the live enum here would silently rewrite
# history - a Phase 6 enum member would appear in a Phase 5 migration's constraint,
# and re-running the migration on a clean database would produce a constraint that
# Phase 5 never had.
#
# These strings are asserted equal to the enums by the data-layer tests, so the
# duplication cannot drift unnoticed.
# ---------------------------------------------------------------------------
PAYMENT_CHANNELS = ("MOCK", "ALIPAY", "WECHAT")
PAYMENT_RECORD_STATUSES = (
    "INITIATED",
    "PAYING",
    "SUCCESS",
    "FAILED",
    "CLOSED",
    "REFUNDED",
    "PARTIAL_REFUNDED",
)
CALLBACK_PROCESS_STATUSES = ("RECEIVED", "PROCESSED", "FAILED", "IGNORED")
#: Re-exported by the fulfillment module from ``app.modules.order.enums`` - Phase 4
#: froze this vocabulary and Phase 5 only reuses it.
FULFILLMENT_STATUSES = ("UNFULFILLED", "PARTIAL_SHIPPED", "SHIPPED", "DELIVERED")
CARRIER_CODES = ("SF", "YTO", "JD", "ZTO", "STO", "YD", "EMS", "OTHER")
AFTER_SALE_TYPES = ("REFUND_ONLY", "RETURN_REFUND")
AFTER_SALE_CLAIM_STATUSES = ("PENDING", "APPROVED", "REJECTED", "CANCELLED", "COMPLETED")
REFUND_STATUSES = ("PENDING", "SUCCEEDED", "FAILED")
#: Shared with ``order_status_logs`` - one vocabulary for "who caused this row".
OPERATOR_TYPES = ("SYSTEM", "CUSTOMER", "STAFF", "AGENT", "MCP", "WORKER")


def _vocabulary(values: tuple[str, ...]) -> str:
    """Render a tuple as the SQL body of ``IN (...)``."""
    return "(" + ",".join(f"'{value}'" for value in values) + ")"


def upgrade() -> None:
    """Add the two refund caps, then create the six Phase 5 tables."""
    # -----------------------------------------------------------------
    # The two FG-12 caps on the PRE-EXISTING tables.
    #
    # These come first for a reason that is not cosmetic: they are the only
    # statements in this file Alembic cannot see or reproduce. If the migration
    # fails after this point, the partial state is "old tables + new caps", which is
    # exactly what Phase 4's own CHECKs already are (self-consistent rows), whereas
    # failing after the new tables were created would leave them without the caps
    # that FG-12 asserts against them.
    #
    # Both operands are signed BIGINT on both tables (see the docstring), so the
    # plain comparison is arithmetically correct without a CAST.
    #
    # ``op.f(...)`` is **required** here and is not decoration. ``op.create_check_
    # constraint`` runs its name argument through the metadata naming convention
    # again, so passing the final name ``ck_orders_refund_cap`` produced
    # ``ck_orders_ck_orders_refund_cap`` - a constraint the ORM does not know about,
    # which ``alembic check`` then reports as a permanent un-applied diff. ``op.f()``
    # marks the name as already final, exactly as the ``name=op.f(...)`` arguments in
    # ``create_table`` above do. (This was caught by reading the constraint names
    # back from ``information_schema``, not by the migration exiting 0 - which is
    # the whole reason that read-back is part of the task.)
    # -----------------------------------------------------------------
    op.create_check_constraint(
        op.f("ck_orders_refund_cap"),
        "orders",
        "refunded_amount <= paid_amount",
    )
    op.create_check_constraint(
        op.f("ck_order_items_refund_cap"),
        "order_items",
        "refunded_amount <= payable_amount",
    )

    # -----------------------------------------------------------------
    # payments - the money-in record (design section 5.1, REQ-PAY-001)
    # -----------------------------------------------------------------
    op.create_table(
        "payments",
        sa.Column("payment_no", sa.String(length=32), nullable=False),
        sa.Column("order_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("order_no", sa.String(length=32), nullable=False),
        sa.Column("user_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        # Signed BIGINT: see the docstring.
        sa.Column("amount", app.shared.db.types.MoneyMinor(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="INITIATED",
            nullable=False,
        ),
        sa.Column("external_transaction_no", sa.String(length=128), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("client_request_id", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "paid_amount",
            app.shared.db.types.MoneyMinor(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "refunded_amount",
            app.shared.db.types.MoneyMinor(),
            server_default="0",
            nullable=False,
        ),
        sa.Column("expires_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("paid_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("closed_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            app.shared.db.types.DateTimeMS(),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.shared.db.types.DateTimeMS(),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.CheckConstraint(
            f"channel IN {_vocabulary(PAYMENT_CHANNELS)}",
            name=op.f("ck_payments_channel_valid"),
        ),
        sa.CheckConstraint(
            f"status IN {_vocabulary(PAYMENT_RECORD_STATUSES)}",
            name=op.f("ck_payments_status_valid"),
        ),
        # A zero-amount payment would be a free order; a negative one is nonsense in
        # every direction. `amount >= 0` is subsumed by this and deliberately not
        # written - a redundant constraint is another thing to keep in sync by hand.
        sa.CheckConstraint("amount > 0", name=op.f("ck_payments_amount_positive")),
        sa.CheckConstraint(
            "paid_amount >= 0 AND refunded_amount >= 0",
            name=op.f("ck_payments_amounts_non_negative"),
        ),
        # FG-12 cap 1 at the boundary: an operator with a MySQL client cannot refund
        # more than was settled, and neither can an application bug.
        sa.CheckConstraint(
            "refunded_amount <= paid_amount", name=op.f("ck_payments_refund_cap")
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_payments_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_payments_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_payments_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint(
            "merchant_id", "payment_no", name="uq_payments_merchant_payment_no"
        ),
        # The first idempotency guard: a retried create finds this row, not a new one.
        sa.UniqueConstraint(
            "merchant_id", "idempotency_key", name="uq_payments_merchant_idempotency_key"
        ),
        # The second guard: a client that loses its Idempotency-Key header still
        # cannot double-submit.
        sa.UniqueConstraint(
            "user_id", "client_request_id", name="uq_payments_user_client_request"
        ),
    )
    op.create_index("ix_payments_created_at", "payments", ["created_at"], unique=False)
    op.create_index("ix_payments_merchant_id", "payments", ["merchant_id"], unique=False)
    op.create_index(
        "ix_payments_merchant_status", "payments", ["merchant_id", "status"], unique=False
    )
    op.create_index("ix_payments_order_id", "payments", ["order_id"], unique=False)
    op.create_index(
        "ix_payments_order_created", "payments", ["order_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_payments_user_created", "payments", ["user_id", "created_at"], unique=False
    )

    # -----------------------------------------------------------------
    # payment_callbacks - THE idempotency anchor (design section 5.2, REQ-PAY-002/003)
    # -----------------------------------------------------------------
    op.create_table(
        "payment_callbacks",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_event_id", sa.String(length=128), nullable=False),
        sa.Column("payment_no", sa.String(length=32), nullable=True),
        sa.Column("order_no", sa.String(length=32), nullable=True),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        # A *sensitive-field filtered* copy of the provider's body: stored for audit
        # and dispute handling, so it must stay recognisably the provider's payload.
        sa.Column("payload_snapshot", sa.JSON(), nullable=True),
        sa.Column("signature_valid", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "process_status", sa.String(length=16), server_default="RECEIVED", nullable=False
        ),
        sa.Column("process_error", sa.String(length=500), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("received_at", app.shared.db.types.DateTimeMS(), nullable=False),
        sa.Column("processed_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            app.shared.db.types.DateTimeMS(),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.shared.db.types.DateTimeMS(),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            f"process_status IN {_vocabulary(CALLBACK_PROCESS_STATUSES)}",
            name=op.f("ck_payment_callbacks_process_status_valid"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 1", name=op.f("ck_payment_callbacks_attempt_count_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_callbacks")),
        # THE serialisation point of FG-11. Deliberately global rather than
        # merchant-scoped: an event id is unique at the provider, and scoping it by
        # merchant would let one event insert twice under two merchants - precisely
        # the double-settlement this phase is built to prevent. No FK to `payments`
        # either; see the docstring.
        sa.UniqueConstraint(
            "provider", "provider_event_id", name="uq_payment_callbacks_provider_event"
        ),
    )
    op.create_index(
        "ix_payment_callbacks_created_at", "payment_callbacks", ["created_at"], unique=False
    )
    op.create_index(
        "ix_payment_callbacks_merchant_id", "payment_callbacks", ["merchant_id"], unique=False
    )
    op.create_index(
        "ix_payment_callbacks_payment_no", "payment_callbacks", ["payment_no"], unique=False
    )
    op.create_index(
        "ix_payment_callbacks_process_status",
        "payment_callbacks",
        ["process_status"],
        unique=False,
    )
    op.create_index(
        "ix_payment_callbacks_received_at", "payment_callbacks", ["received_at"], unique=False
    )

    # -----------------------------------------------------------------
    # fulfillments / fulfillment_items - goods out (design section 5.4, REQ-FUL-001/002)
    # -----------------------------------------------------------------
    op.create_table(
        "fulfillments",
        sa.Column("fulfillment_no", sa.String(length=32), nullable=False),
        sa.Column("order_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("order_no", sa.String(length=32), nullable=False),
        sa.Column("warehouse_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column(
            "fulfillment_status",
            sa.String(length=32),
            server_default="UNFULFILLED",
            nullable=False,
        ),
        sa.Column("carrier", sa.String(length=16), nullable=True),
        sa.Column("tracking_no", sa.String(length=64), nullable=True),
        sa.Column("package_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("remark", sa.String(length=500), nullable=True),
        sa.Column("shipped_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("delivered_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            app.shared.db.types.DateTimeMS(),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.shared.db.types.DateTimeMS(),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.CheckConstraint(
            f"fulfillment_status IN {_vocabulary(FULFILLMENT_STATUSES)}",
            name=op.f("ck_fulfillments_fulfillment_status_valid"),
        ),
        # NULL is valid (nobody has shipped it); a free-text carrier is what this
        # rejects, because the console renders a select and a later phase must map the
        # code back to a carrier.
        sa.CheckConstraint(
            f"carrier IS NULL OR carrier IN {_vocabulary(CARRIER_CODES)}",
            name=op.f("ck_fulfillments_carrier_valid"),
        ),
        sa.CheckConstraint(
            "package_count >= 1", name=op.f("ck_fulfillments_package_count_positive")
        ),
        # A shipped/delivered package must actually carry shipment data. Without this,
        # a status write alone could claim goods left while the customer's tracking
        # view has neither carrier nor tracking number - a "ghost shipment", which is
        # worse than an unshipped one because it is invisible in the fulfillment
        # queue. `ShipWorkflow` stamps all three in one write, so it holds by
        # construction.
        sa.CheckConstraint(
            "fulfillment_status NOT IN ('SHIPPED','DELIVERED') "
            "OR (carrier IS NOT NULL AND tracking_no IS NOT NULL AND shipped_at IS NOT NULL)",
            name=op.f("ck_fulfillments_shipment_data_required"),
        ),
        # A package that has not shipped cannot already have been delivered.
        sa.CheckConstraint(
            "delivered_at IS NULL OR shipped_at IS NOT NULL",
            name=op.f("ck_fulfillments_delivered_after_shipped"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_fulfillments_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_fulfillments_order_id_orders"),
            ondelete="RESTRICT",
        ),
        # The deduction target: a package that cannot name its warehouse cannot be
        # reconciled against the stock ledger (INV-007).
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_fulfillments_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fulfillments")),
        # NO unique on order_id: one order may ship several packages (REQ-FUL-001),
        # and a UNIQUE would make a split shipment unrecordable without a migration.
        sa.UniqueConstraint(
            "merchant_id", "fulfillment_no", name="uq_fulfillments_merchant_fulfillment_no"
        ),
    )
    op.create_index(
        "ix_fulfillments_created_at", "fulfillments", ["created_at"], unique=False
    )
    op.create_index("ix_fulfillments_merchant_id", "fulfillments", ["merchant_id"], unique=False)
    op.create_index(
        "ix_fulfillments_merchant_status",
        "fulfillments",
        ["merchant_id", "fulfillment_status"],
        unique=False,
    )
    op.create_index("ix_fulfillments_order_id", "fulfillments", ["order_id"], unique=False)
    op.create_index(
        "ix_fulfillments_order_created", "fulfillments", ["order_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_fulfillments_warehouse_id", "fulfillments", ["warehouse_id"], unique=False
    )

    op.create_table(
        "fulfillment_items",
        sa.Column("fulfillment_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("order_item_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        # The ordered line's SKU, snapshotted beside the two names below it. Ruled in,
        # briefly withdrawn in favour of deriving it from `order_items.sku_id` on the
        # read path, then restored by the captain: a snapshot row that carries a line's
        # names but not the id they came from is the one inconsistent combination.
        sa.Column("sku_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("product_name", sa.String(length=200), nullable=False),
        sa.Column("sku_name", sa.String(length=200), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            app.shared.db.types.DateTimeMS(),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.shared.db.types.DateTimeMS(),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_fulfillment_items_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["fulfillment_id"],
            ["fulfillments.id"],
            name=op.f("fk_fulfillment_items_fulfillment_id_fulfillments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.id"],
            name=op.f("fk_fulfillment_items_order_item_id_order_items"),
            ondelete="RESTRICT",
        ),
        # RESTRICT, like every other reference in this phase. A mutating referential
        # action would be rejected by MySQL 8 (errno 3823) in any case: the column
        # participates in a CHECK-bearing table.
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["product_skus.id"],
            name=op.f("fk_fulfillment_items_sku_id_product_skus"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fulfillment_items")),
        # A duplicate line inside ONE package would let a single package over-ship a
        # line while each row individually looked valid. The cumulative rule across
        # packages is a sum over rows and lives in `ShipWorkflow` (70001).
        sa.UniqueConstraint(
            "fulfillment_id", "order_item_id", name="uq_fulfillment_items_package_line"
        ),
    )
    op.create_index(
        "ix_fulfillment_items_created_at", "fulfillment_items", ["created_at"], unique=False
    )
    op.create_index(
        "ix_fulfillment_items_fulfillment_id",
        "fulfillment_items",
        ["fulfillment_id"],
        unique=False,
    )
    op.create_index(
        "ix_fulfillment_items_sku_id",
        "fulfillment_items",
        ["sku_id"],
        unique=False,
    )
    # -----------------------------------------------------------------
    # `fulfillment_items.sku_id`: backfill, then tighten to NOT NULL.
    #
    # The column is created NULLABLE above and tightened here rather than declared
    # NOT NULL in `create_table`, and that is not a stylistic choice. MySQL runs this
    # server in STRICT_TRANS_TABLES (verified: `SELECT @@sql_mode`), and under strict
    # mode `ALTER TABLE ... ADD COLUMN ... NOT NULL` on a table that already holds rows
    # **fails** rather than filling in a default. A migration that only works on an
    # empty table is a migration that breaks the first time it meets a populated
    # database - which is precisely the situation this revision is re-applied into,
    # because the ship path had already written package lines.
    #
    # The backfill reads `order_items.sku_id`, which is the authoritative value and is
    # guaranteed present: `order_item_id` is NOT NULL with a RESTRICT FK to
    # `order_items`, so every existing row resolves. `order_items` is itself a snapshot
    # table, so this does not introduce a catalogue read (INV-014).
    # -----------------------------------------------------------------
    op.execute(
        """
        UPDATE fulfillment_items fi
          JOIN order_items oi ON oi.id = fi.order_item_id
           SET fi.sku_id = oi.sku_id
         WHERE fi.sku_id IS NULL
        """
    )
    op.alter_column(
        "fulfillment_items",
        "sku_id",
        existing_type=app.shared.db.types.BigIntUnsigned(),
        nullable=False,
    )
    op.create_index(
        "ix_fulfillment_items_order_item_id",
        "fulfillment_items",
        ["order_item_id"],
        unique=False,
    )

    # -----------------------------------------------------------------
    # after_sales / after_sale_items - the claim (design section 5.5, REQ-AFS-001)
    # -----------------------------------------------------------------
    op.create_table(
        "after_sales",
        sa.Column("after_sale_no", sa.String(length=32), nullable=False),
        sa.Column("order_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("order_no", sa.String(length=32), nullable=False),
        sa.Column("user_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column(
            "claim_status", sa.String(length=16), server_default="PENDING", nullable=False
        ),
        sa.Column("requested_amount", app.shared.db.types.MoneyMinor(), nullable=False),
        sa.Column(
            "approved_amount",
            app.shared.db.types.MoneyMinor(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "refunded_amount",
            app.shared.db.types.MoneyMinor(),
            server_default="0",
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("evidence_urls", sa.JSON(), nullable=True),
        sa.Column("reject_reason", sa.String(length=500), nullable=True),
        sa.Column("processed_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("completed_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("client_request_id", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            app.shared.db.types.DateTimeMS(),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.shared.db.types.DateTimeMS(),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.CheckConstraint(
            f"type IN {_vocabulary(AFTER_SALE_TYPES)}",
            name=op.f("ck_after_sales_type_valid"),
        ),
        sa.CheckConstraint(
            f"claim_status IN {_vocabulary(AFTER_SALE_CLAIM_STATUSES)}",
            name=op.f("ck_after_sales_claim_status_valid"),
        ),
        # NOTE what is deliberately absent here: `refunded_amount <= approved_amount
        # <= requested_amount` is NOT a constraint. Design section 5.5: an operator
        # may approve more than was requested when policy allows it, which V1 forbids
        # in the service rather than in the schema. A policy question must not become
        # a migration on the hot path.
        sa.CheckConstraint(
            "requested_amount >= 0 AND approved_amount >= 0 AND refunded_amount >= 0",
            name=op.f("ck_after_sales_amounts_non_negative"),
        ),
        sa.CheckConstraint(
            "claim_status <> 'REJECTED' OR reject_reason IS NOT NULL",
            name=op.f("ck_after_sales_reject_reason_required"),
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR processed_at IS NOT NULL",
            name=op.f("ck_after_sales_completed_after_processed"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_after_sales_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_after_sales_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_after_sales_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_after_sales")),
        sa.UniqueConstraint(
            "merchant_id", "after_sale_no", name="uq_after_sales_merchant_after_sale_no"
        ),
        sa.UniqueConstraint(
            "merchant_id",
            "idempotency_key",
            name="uq_after_sales_merchant_idempotency_key",
        ),
        sa.UniqueConstraint(
            "user_id", "client_request_id", name="uq_after_sales_user_client_request"
        ),
    )
    op.create_index("ix_after_sales_created_at", "after_sales", ["created_at"], unique=False)
    op.create_index("ix_after_sales_merchant_id", "after_sales", ["merchant_id"], unique=False)
    op.create_index(
        "ix_after_sales_merchant_status",
        "after_sales",
        ["merchant_id", "claim_status"],
        unique=False,
    )
    op.create_index("ix_after_sales_order_id", "after_sales", ["order_id"], unique=False)
    op.create_index(
        "ix_after_sales_order_created", "after_sales", ["order_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_after_sales_user_created", "after_sales", ["user_id", "created_at"], unique=False
    )

    op.create_table(
        "after_sale_items",
        sa.Column("after_sale_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("order_item_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("product_name", sa.String(length=200), nullable=False),
        sa.Column("sku_name", sa.String(length=200), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            app.shared.db.types.DateTimeMS(),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.shared.db.types.DateTimeMS(),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_after_sale_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["after_sale_id"],
            ["after_sales.id"],
            name=op.f("fk_after_sale_items_after_sale_id_after_sales"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.id"],
            name=op.f("fk_after_sale_items_order_item_id_order_items"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_after_sale_items")),
        sa.UniqueConstraint(
            "after_sale_id", "order_item_id", name="uq_after_sale_items_claim_line"
        ),
    )
    op.create_index(
        "ix_after_sale_items_after_sale_id", "after_sale_items", ["after_sale_id"], unique=False
    )
    op.create_index(
        "ix_after_sale_items_created_at", "after_sale_items", ["created_at"], unique=False
    )
    op.create_index(
        "ix_after_sale_items_order_item_id",
        "after_sale_items",
        ["order_item_id"],
        unique=False,
    )

    # -----------------------------------------------------------------
    # refunds - the money-out record (design sections 5.5, 4.3, 6.2 / FG-12)
    # -----------------------------------------------------------------
    op.create_table(
        "refunds",
        sa.Column("refund_no", sa.String(length=32), nullable=False),
        sa.Column("after_sale_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("order_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("order_no", sa.String(length=32), nullable=False),
        # NULLABLE on purpose: Phase 4's orders predate payment records, and a
        # legacy/manual adjustment may legitimately have no payment row to name. A
        # required FK would make that adjustment unrecordable rather than visibly
        # unusual.
        sa.Column("payment_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("user_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("amount", app.shared.db.types.MoneyMinor(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="PENDING", nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("operator_type", sa.String(length=32), nullable=False),
        sa.Column("operator_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("completed_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            app.shared.db.types.DateTimeMS(),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.shared.db.types.DateTimeMS(),
            server_default=sa.text("now(3)"),
            nullable=False,
        ),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.CheckConstraint(
            f"status IN {_vocabulary(REFUND_STATUSES)}",
            name=op.f("ck_refunds_status_valid"),
        ),
        # A zero refund is refused earlier (REFUND_AMOUNT_INVALID, 80006); the
        # constraint is here so no code path can store one anyway.
        sa.CheckConstraint("amount > 0", name=op.f("ck_refunds_amount_positive")),
        sa.CheckConstraint(
            f"operator_type IN {_vocabulary(OPERATOR_TYPES)}",
            name=op.f("ck_refunds_operator_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["after_sale_id"],
            ["after_sales.id"],
            name=op.f("fk_refunds_after_sale_id_after_sales"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_refunds_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_refunds_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=op.f("fk_refunds_payment_id_payments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refunds_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refunds")),
        sa.UniqueConstraint("merchant_id", "refund_no", name="uq_refunds_merchant_refund_no"),
        # Note there is no `UNIQUE (user_id, client_request_id)` here, unlike
        # `orders`/`payments`/`after_sales`: the refund endpoint's idempotency is the
        # `Idempotency-Key` alone (design section 6.2 step 1), because the operator's
        # console has no client-generated request id of its own.
        sa.UniqueConstraint(
            "merchant_id", "idempotency_key", name="uq_refunds_merchant_idempotency_key"
        ),
    )
    op.create_index(
        "ix_refunds_after_sale_id", "refunds", ["after_sale_id"], unique=False
    )
    op.create_index("ix_refunds_created_at", "refunds", ["created_at"], unique=False)
    op.create_index("ix_refunds_merchant_id", "refunds", ["merchant_id"], unique=False)
    op.create_index("ix_refunds_order_id", "refunds", ["order_id"], unique=False)
    op.create_index(
        "ix_refunds_order_created", "refunds", ["order_id", "created_at"], unique=False
    )
    op.create_index("ix_refunds_payment_id", "refunds", ["payment_id"], unique=False)
    op.create_index(
        "ix_refunds_user_created", "refunds", ["user_id", "created_at"], unique=False
    )


def downgrade() -> None:
    """Remove the two caps, then drop the six Phase 5 tables in reverse FK order.

    The constraint drops come **first**, and that ordering is deliberate rather than
    incidental: they are on tables this migration does not own, so removing them
    before touching the new tables means the pre-existing schema is returned to its
    Phase 4 shape before anything else moves. It also means the downgrade's first
    statement is the one that fails loudly (a candidate key, a lock wait) rather than
    the last, when half the work is already irreversible - MySQL DDL is
    non-transactional, so there is no rollback to fall back on.

    `refunds` references `payments` and `after_sales`, so it goes before both.
    `fulfillment_items` / `after_sale_items` reference `order_items`, which this
    migration does not drop. There are no `op.drop_index` calls: `DROP TABLE`
    removes a table's indexes with it, and doing it separately is what broke the
    Phase 4 downgrade with errno 1553 (see the module docstring).

    ``op.f(...)`` on the two constraint names is **required**, for the same reason as
    in ``upgrade()``: ``op.drop_constraint`` runs its name through the metadata
    naming convention again and would emit
    ``ALTER TABLE order_items DROP CHECK ck_order_items_ck_order_items_refund_cap`` -
    a constraint that does not exist, so MySQL answers errno 3821 and the downgrade
    aborts with the Phase 5 tables still in place. Because MySQL DDL is
    non-transactional, that abort leaves the database *behind* ``alembic_version``:
    every later ``upgrade`` becomes a no-op, the schema never converges, and the
    failure looks like a phantom because the names in the database and the names in
    the source are both correct. It was found by running ``downgrade -1`` for real
    and reading the emitted SQL with ``--sql``, which is why the round trip is part
    of the task rather than an assumption.
    """
    op.drop_constraint(op.f("ck_order_items_refund_cap"), "order_items", type_="check")
    op.drop_constraint(op.f("ck_orders_refund_cap"), "orders", type_="check")

    # The column is dropped with `fulfillment_items` below, so no explicit drop is
    # needed - and asking for one would fail for the same reason Phase 4's index drops
    # failed (errno 1553): the FK's supporting index is removed by DROP TABLE, not by a
    # separate DROP INDEX.
    op.drop_table("refunds")
    op.drop_table("after_sale_items")
    op.drop_table("after_sales")
    op.drop_table("fulfillment_items")
    op.drop_table("fulfillments")
    op.drop_table("payment_callbacks")
    op.drop_table("payments")
