"""identity_and_auth_sessions

Revision ID: 678c0e1de548
Revises:
Create Date: 2026-09-23 07:40:46.311651

Generated by Alembic. Review before committing - autogenerate is a draft, not a
verdict. In particular, verify that:

  * the downgrade path is genuinely correct (it is the disaster-recovery path);
  * CHECK constraints backing INV-001/INV-002 were not silently dropped;
  * money columns are BIGINT and never FLOAT/DOUBLE (spec section 19);
  * new columns on populated tables are nullable, or carry a server_default.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.shared.db.types

# revision identifiers, used by Alembic.
revision: str = "678c0e1de548"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchants",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="ACTIVE", nullable=False),
        sa.Column("commission_bps", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column("deleted_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.CheckConstraint("length(code) >= 2", name=op.f("ck_merchants_code_min_length")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchants")),
        sa.UniqueConstraint("code", name="uq_merchants_code"),
    )
    op.create_index(op.f("ix_merchants_created_at"), "merchants", ["created_at"], unique=False)
    op.create_index(op.f("ix_merchants_deleted_at"), "merchants", ["deleted_at"], unique=False)
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=96), nullable=False),
        sa.Column("resource", sa.String(length=48), nullable=False),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_grantable", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("code", name="uq_permissions_code"),
    )
    op.create_index(op.f("ix_permissions_created_at"), "permissions", ["created_at"], unique=False)
    op.create_index("ix_permissions_resource", "permissions", ["resource"], unique=False)
    op.create_table(
        "roles",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_system", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("data_scope", sa.String(length=32), server_default="SELF", nullable=False),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.CheckConstraint("is_system = 1 OR is_system = 0", name=op.f("ck_roles_is_system_boolean")),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_roles_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", "merchant_id", name="uq_roles_code_merchant"),
    )
    op.create_index(op.f("ix_roles_created_at"), "roles", ["created_at"], unique=False)
    op.create_index(op.f("ix_roles_merchant_id"), "roles", ["merchant_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("user_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="ACTIVE", nullable=False),
        sa.Column("data_scope_override", sa.String(length=32), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_until", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("last_login_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("password_changed_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("deleted_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.CheckConstraint(
            "(user_type = 'CONSUMER') OR (user_type = 'STAFF' AND merchant_id IS NOT NULL)",
            name=op.f("ck_users_staff_requires_merchant"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','INACTIVE','LOCKED','DISABLED')", name=op.f("ck_users_status_valid")
        ),
        sa.CheckConstraint("user_type IN ('CONSUMER','STAFF')", name=op.f("ck_users_user_type_valid")),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_users_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.UniqueConstraint("phone", name="uq_users_phone"),
        sa.UniqueConstraint("username", name="uq_users_username"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_users_merchant_id"), "users", ["merchant_id"], unique=False)
    op.create_index("ix_users_merchant_status", "users", ["merchant_id", "status"], unique=False)
    op.create_table(
        "auth_sessions",
        sa.Column("user_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=64), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("issued_at", app.shared.db.types.DateTimeMS(), nullable=False),
        sa.Column("expires_at", app.shared.db.types.DateTimeMS(), nullable=False),
        sa.Column("revoked_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("rotated_from", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("revoked_reason", sa.String(length=32), nullable=True),
        sa.Column("last_used_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("client_ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("login_source", sa.String(length=32), nullable=True),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.CheckConstraint(
            "revoked_at IS NULL OR revoked_at >= created_at",
            name=op.f("ck_auth_sessions_revoked_after_created"),
        ),
        sa.ForeignKeyConstraint(
            ["rotated_from"],
            ["auth_sessions.id"],
            name=op.f("fk_auth_sessions_rotated_from_auth_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("jti", name="uq_auth_sessions_jti"),
        sa.UniqueConstraint("refresh_token_hash", name="uq_auth_sessions_refresh_token_hash"),
        sa.UniqueConstraint("session_id", name="uq_auth_sessions_session_id"),
    )
    op.create_index(op.f("ix_auth_sessions_created_at"), "auth_sessions", ["created_at"], unique=False)
    op.create_index("ix_auth_sessions_expires", "auth_sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False)
    op.create_index("ix_auth_sessions_user_revoked", "auth_sessions", ["user_id", "revoked_at"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("permission_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("granted_by", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
            name=op.f("fk_role_permissions_granted_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_role_permissions_role_id_roles"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_permissions")),
        sa.UniqueConstraint("role_id", "permission_id", name="uq_role_permissions_role_permission"),
    )
    op.create_index(op.f("ix_role_permissions_created_at"), "role_permissions", ["created_at"], unique=False)
    op.create_index("ix_role_permissions_permission", "role_permissions", ["permission_id"], unique=False)
    op.create_index(op.f("ix_role_permissions_role_id"), "role_permissions", ["role_id"], unique=False)
    op.create_table(
        "user_addresses",
        sa.Column("user_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("receiver_name", sa.String(length=64), nullable=False),
        sa.Column("receiver_phone", sa.String(length=32), nullable=False),
        sa.Column("province", sa.String(length=64), nullable=False),
        sa.Column("city", sa.String(length=64), nullable=False),
        sa.Column("district", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.String(length=255), nullable=False),
        sa.Column("postal_code", sa.String(length=16), nullable=True),
        sa.Column("tag", sa.String(length=32), server_default="HOME", nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column("merchant_id", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("deleted_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.CheckConstraint(
            "tag IN ('HOME','OFFICE','SCHOOL','OTHER')", name=op.f("ck_user_addresses_tag_valid")
        ),
        sa.CheckConstraint("length(receiver_name) > 0", name=op.f("ck_user_addresses_receiver_name_present")),
        sa.CheckConstraint(
            "length(receiver_phone) >= 6", name=op.f("ck_user_addresses_receiver_phone_present")
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_user_addresses_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_addresses_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_addresses")),
    )
    op.create_index(op.f("ix_user_addresses_created_at"), "user_addresses", ["created_at"], unique=False)
    op.create_index(op.f("ix_user_addresses_deleted_at"), "user_addresses", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_user_addresses_merchant_id"), "user_addresses", ["merchant_id"], unique=False)
    op.create_index(
        "ix_user_addresses_user_default", "user_addresses", ["user_id", "is_default"], unique=False
    )
    op.create_index(op.f("ix_user_addresses_user_id"), "user_addresses", ["user_id"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("user_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("role_id", app.shared.db.types.BigIntUnsigned(), nullable=False),
        sa.Column("granted_by", app.shared.db.types.BigIntUnsigned(), nullable=True),
        sa.Column("expires_at", app.shared.db.types.DateTimeMS(), nullable=True),
        sa.Column("id", app.shared.db.types.BigIntUnsigned(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.Column(
            "updated_at", app.shared.db.types.DateTimeMS(), server_default=sa.text("now(3)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"], ["users.id"], name=op.f("fk_user_roles_granted_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_roles")),
        sa.UniqueConstraint("user_id", "role_id", name="uq_user_roles_user_role"),
    )
    op.create_index(op.f("ix_user_roles_created_at"), "user_roles", ["created_at"], unique=False)
    op.create_index("ix_user_roles_role", "user_roles", ["role_id"], unique=False)
    op.create_index(op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the change.

    Written out rather than left empty: an unrunnable downgrade turns a bad
    deploy into an unrecoverable one.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
    op.drop_index("ix_user_roles_role", table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_created_at"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_user_addresses_user_id"), table_name="user_addresses")
    op.drop_index("ix_user_addresses_user_default", table_name="user_addresses")
    op.drop_index(op.f("ix_user_addresses_merchant_id"), table_name="user_addresses")
    op.drop_index(op.f("ix_user_addresses_deleted_at"), table_name="user_addresses")
    op.drop_index(op.f("ix_user_addresses_created_at"), table_name="user_addresses")
    op.drop_table("user_addresses")
    op.drop_index(op.f("ix_role_permissions_role_id"), table_name="role_permissions")
    op.drop_index("ix_role_permissions_permission", table_name="role_permissions")
    op.drop_index(op.f("ix_role_permissions_created_at"), table_name="role_permissions")
    op.drop_table("role_permissions")
    op.drop_index("ix_auth_sessions_user_revoked", table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index("ix_auth_sessions_expires", table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_created_at"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index("ix_users_merchant_status", table_name="users")
    op.drop_index(op.f("ix_users_merchant_id"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_roles_merchant_id"), table_name="roles")
    op.drop_index(op.f("ix_roles_created_at"), table_name="roles")
    op.drop_table("roles")
    op.drop_index("ix_permissions_resource", table_name="permissions")
    op.drop_index(op.f("ix_permissions_created_at"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_merchants_deleted_at"), table_name="merchants")
    op.drop_index(op.f("ix_merchants_created_at"), table_name="merchants")
    op.drop_table("merchants")
    # ### end Alembic commands ###
