"""ledger_quantities_signed_bigint

Revision ID: 5cbebbc7b364
Revises: 05b3d5f5348b
Create Date: 2026-09-23 12:35:39.148672

Generated by Alembic. Review before committing - autogenerate is a draft, not a
verdict. In particular, verify that:

  * the downgrade path is genuinely correct (it is the disaster-recovery path);
  * CHECK constraints backing INV-001/INV-002 were not silently dropped;
  * money columns are BIGINT and never FLOAT/DOUBLE (spec section 19);
  * new columns on populated tables are nullable, or carry a server_default.
"""

from __future__ import annotations

from collections.abc import Sequence

# revision identifiers, used by Alembic.
import sqlalchemy as sa
from alembic import op


revision: str = "5cbebbc7b364"
down_revision: str | None = "05b3d5f5348b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Make the ledger's quantity columns SIGNED.

    Written by hand for two reasons, both discovered the hard way while getting
    FG-09 to pass:

    1. Alembic did **not** autogenerate this change. `compare_type=True` does not
       distinguish `BIGINT` from `BIGINT UNSIGNED` on MySQL, so the generated
       migration was empty and the columns silently stayed unsigned.
    2. Alembic also does not autogenerate **CHECK-constraint** changes on MySQL.
       An earlier attempt to fix the same problem by adding CASTs inside the
       constraint therefore never reached the database either.

    The underlying issue: `delta_*` is signed (a delta is legitimately negative)
    while `before_*`/`after_*` were BIGINT UNSIGNED, and MySQL promotes a mixed
    comparison to unsigned - so `0 - 1` overflowed and the delta-consistency
    CHECK rejected rows that were arithmetically correct. Making every operand
    signed puts the arithmetic on solid ground.

    `delta_available`/`delta_locked` are already signed INT; before/after are
    bounded by the inventory row they describe, so unsigned bought nothing here.
    """
    op.execute(
        """
        ALTER TABLE inventory_movements
            MODIFY before_available BIGINT NOT NULL,
            MODIFY after_available  BIGINT NOT NULL,
            MODIFY before_locked    BIGINT NOT NULL,
            MODIFY after_locked     BIGINT NOT NULL
        """
    )


def downgrade() -> None:
    """Restore the unsigned columns (and with them, the promotion bug)."""
    op.execute(
        """
        ALTER TABLE inventory_movements
            MODIFY before_available BIGINT UNSIGNED NOT NULL,
            MODIFY after_available  BIGINT UNSIGNED NOT NULL,
            MODIFY before_locked    BIGINT UNSIGNED NOT NULL,
            MODIFY after_locked     BIGINT UNSIGNED NOT NULL
        """
    )


